### ISSUE TITLE
Master ToDo List

### ISSUE THREAD

**Issue by Guard13007** [cc-paw/cc-paw-new#1]
- [ ] Feature: Files that get installed once and are not intended to be upgraded.
- [ ] Feature: Packages can define how much space they need to install.
- [ ] Feature: Maintainer listed separately from author.
- [ ] Specify something `/bin` for binaries, `/lib` for libraries, `/etc` for configuration files, `/tmp` for temporary files. Roughly following the [FSH]()
- [ ] The `pkg.lua` of an installed package should be saved in `/etc/cc-paw/NAME/pkg.lua` as it contains information needed for uninstallation, upgrading, and purging.
- [ ] Document: Explain how the `pkg.lua` files work instead of *just* relying on my example file.
- [ ] Use LDoc to document how it works, use a minification system (and build script) to build versions.

**Comment by Guard13007** [comment]
Extra ideas:

- [ ] Feature: `source` command to get source of packages? Kinda don't see the need.

**Comment by Guard13007** [comment]
Note on submodules: https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

**Comment by Guard13007** [comment]
- [ ] cc-paw post-installation script to ask if user wants to install the installer as a backup?
- [ ] make the cc-paw installer available as a package

**Comment by Guard13007** [comment]
- [ ] Package: Disk usage analyser.

**Comment by Guard13007** [comment]
- [ ] Package: `fsdb` Fake SQL using files to store data. Or something like that. Idk exactly.
- [ ] Package: `lynx` Minimalist web browser, based on Lynx.
- [ ] Package: RedNet Browser..or whatever. Find the latest working version and fix and improve it.
- [ ] Feature: Maintainer listed as well as author.

**Comment by Guard13007** [comment]
(Remember, checked means implemented or abandoned.)

**Comment by Guard13007** [comment]
- [ ] Use a build system to make minified version available. Installed via a forced install option from cc-paw and installs on top of cc-paw. (Note to self: Make sure forced installations go around files already existing.)
